import { z } from "zod";

export const createTaskSchema = z.object({
    userId: z.string().min(1, "User ID is required"),
    title: z.string().min(1, "Title is required").max(255, "Title must be at most 255 characters"),
    description: z.string().max(5000, "Description must be at most 5000 characters").optional().nullable(),
    priority: z.enum(["none", "low", "medium", "high"]).default("none").optional(),
    dueDate: z.coerce.date().optional().nullable(),
    dueDatePrecision: z.enum(["day", "week", "month", "year"]).optional().nullable(),
    deadline: z.coerce.date().optional().nullable(),
    listId: z.number().optional().nullable(),
    labelIds: z.array(z.number()).optional(),
    isRecurring: z.boolean().optional(),
    recurringRule: z.string().max(255, "Recurring rule must be at most 255 characters").optional().nullable(),
    parentId: z.number().optional().nullable(),
    estimateMinutes: z.number().optional().nullable(),
    actualMinutes: z.number().optional().nullable(),
    isCompleted: z.boolean().optional(),
    completedAt: z.coerce.date().optional().nullable(),
    energyLevel: z.enum(["low", "medium", "high"]).optional().nullable(),
    context: z.enum(["computer", "phone", "errands", "meeting", "home", "anywhere"]).optional().nullable(),
    isHabit: z.boolean().optional(),
    icon: z.string().max(255, "Icon must be at most 255 characters").optional().nullable(),
});

export const updateTaskSchema = z.object({
    title: z.string().min(1, "Title cannot be empty").max(255, "Title must be at most 255 characters").optional(),
    description: z.string().max(5000, "Description must be at most 5000 characters").optional().nullable(),
    priority: z.enum(["none", "low", "medium", "high"]).optional(),
    dueDate: z.coerce.date().optional().nullable(),
    dueDatePrecision: z.enum(["day", "week", "month", "year"]).optional().nullable(),
    deadline: z.coerce.date().optional().nullable(),
    listId: z.number().optional().nullable(),
    labelIds: z.array(z.number()).optional(),
    isRecurring: z.boolean().optional(),
    recurringRule: z.string().max(255, "Recurring rule must be at most 255 characters").optional().nullable(),
    parentId: z.number().optional().nullable(),
    estimateMinutes: z.number().optional().nullable(),
    actualMinutes: z.number().optional().nullable(),
    isCompleted: z.boolean().optional(),
    completedAt: z.coerce.date().optional().nullable(),
    energyLevel: z.enum(["low", "medium", "high"]).optional().nullable(),
    context: z.string().max(255).optional().nullable(),
    isHabit: z.boolean().optional(),
    icon: z.string().max(255, "Icon must be at most 255 characters").optional().nullable(),
    expectedUpdatedAt: z.coerce.date().optional().nullable(),
});
