import { z } from "zod";

export const createTaskSchema = z.object({
    userId: z.string().min(1, "User ID is required"),
    title: z.string().min(1, "Title is required"),
    description: z.string().optional().nullable(),
    priority: z.enum(["none", "low", "medium", "high"]).default("none").optional(),
    dueDate: z.coerce.date().optional().nullable(),
    deadline: z.coerce.date().optional().nullable(),
    listId: z.number().optional().nullable(),
    labelIds: z.array(z.number()).optional(),
    isRecurring: z.boolean().optional(),
    recurringRule: z.string().optional().nullable(),
    parentId: z.number().optional().nullable(),
    estimateMinutes: z.number().optional().nullable(),
    actualMinutes: z.number().optional().nullable(),
    isCompleted: z.boolean().optional(),
    completedAt: z.coerce.date().optional().nullable(),
    energyLevel: z.enum(["low", "medium", "high"]).optional().nullable(),
    context: z.string().optional().nullable(),
    isHabit: z.boolean().optional(),
    icon: z.string().optional().nullable(),
});

export const updateTaskSchema = z.object({
    title: z.string().min(1, "Title cannot be empty").optional(),
    description: z.string().optional().nullable(),
    priority: z.enum(["none", "low", "medium", "high"]).optional(),
    dueDate: z.coerce.date().optional().nullable(),
    deadline: z.coerce.date().optional().nullable(),
    listId: z.number().optional().nullable(),
    labelIds: z.array(z.number()).optional(),
    isRecurring: z.boolean().optional(),
    recurringRule: z.string().optional().nullable(),
    parentId: z.number().optional().nullable(),
    estimateMinutes: z.number().optional().nullable(),
    actualMinutes: z.number().optional().nullable(),
    isCompleted: z.boolean().optional(),
    completedAt: z.coerce.date().optional().nullable(),
    energyLevel: z.enum(["low", "medium", "high"]).optional().nullable(),
    context: z.string().optional().nullable(),
    isHabit: z.boolean().optional(),
    icon: z.string().optional().nullable(),
    expectedUpdatedAt: z.coerce.date().optional().nullable(),
});
