-- Migration 0001: Add multi-user support
-- This migration is designed to be resilient for databases created with db:push
--
-- NOTE: This migration uses IF EXISTS, IF NOT EXISTS, and exception handling
-- to be idempotent. This is a one-time transitional migration for databases
-- that were created with db:push before proper migrations were set up.
-- Future migrations generated by `bun run db:generate` will be simpler and
-- won't need this complexity.

-- Step 1: Create users table first (other tables will reference it)
CREATE TABLE IF NOT EXISTS "users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"first_name" text,
	"last_name" text,
	"avatar_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint

-- Step 2: Drop old constraints that will be replaced
ALTER TABLE "lists" DROP CONSTRAINT IF EXISTS "lists_slug_unique";--> statement-breakpoint
ALTER TABLE "user_achievements" DROP CONSTRAINT IF EXISTS "user_achievements_achievement_id_pk";--> statement-breakpoint
ALTER TABLE "view_settings" DROP CONSTRAINT IF EXISTS "view_settings_pkey";--> statement-breakpoint
ALTER TABLE "user_stats" DROP CONSTRAINT IF EXISTS "user_stats_pkey";--> statement-breakpoint

-- Step 3: Add user_id columns to all tables BEFORE adding constraints
DO $$ BEGIN
    ALTER TABLE "labels" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "lists" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "task_logs" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "tasks" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "templates" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "user_achievements" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "user_stats" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "view_settings" ADD COLUMN "user_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "view_settings" ADD COLUMN "view_id" text;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;--> statement-breakpoint

-- Step 4: Drop old columns
ALTER TABLE "user_stats" DROP COLUMN IF EXISTS "id";--> statement-breakpoint
ALTER TABLE "view_settings" DROP COLUMN IF EXISTS "id";--> statement-breakpoint

-- Step 5: Add primary key constraints (now that columns exist)
DO $$ BEGIN
    ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_user_id_achievement_id_pk" PRIMARY KEY("user_id","achievement_id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "view_settings" ADD CONSTRAINT "view_settings_user_id_view_id_pk" PRIMARY KEY("user_id","view_id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "user_stats" ADD CONSTRAINT "user_stats_pkey" PRIMARY KEY("user_id");
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint

-- Step 6: Add foreign key constraints
DO $$ BEGIN
    ALTER TABLE "labels" ADD CONSTRAINT "labels_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "lists" ADD CONSTRAINT "lists_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "task_logs" ADD CONSTRAINT "task_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "tasks" ADD CONSTRAINT "tasks_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "templates" ADD CONSTRAINT "templates_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "user_achievements" ADD CONSTRAINT "user_achievements_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "user_stats" ADD CONSTRAINT "user_stats_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "view_settings" ADD CONSTRAINT "view_settings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint

-- Step 7: Create indexes
CREATE INDEX IF NOT EXISTS "labels_user_id_idx" ON "labels" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lists_user_id_idx" ON "lists" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lists_user_slug_unique" ON "lists" USING btree ("user_id","slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_logs_user_id_idx" ON "task_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tasks_user_id_idx" ON "tasks" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "templates_user_id_idx" ON "templates" USING btree ("user_id");
